// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtuxaekhfwvpwmvmdaul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dXhhZWtoZnd2cHdtdm1kYXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTc1NzMsImV4cCI6MjA2NTQ5MzU3M30.C6vl_5xJ69JuRIwSyK8H_uvdSU6CPEm4lYDkdhGn7lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: Do NOT set a global Content-Type header here. The Supabase JS client
// reuses these headers for every transport, including Storage uploads — forcing
// `Content-Type: application/json` corrupts the MIME of uploaded files
// (e.g. avatars become `application/json` instead of `image/png`).
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);